#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pDaftar3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbReg")]
	public partial class dcReg : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertt_log(t_log instance);
    partial void Updatet_log(t_log instance);
    partial void Deletet_log(t_log instance);
    partial void Insertt_usr(t_usr instance);
    partial void Updatet_usr(t_usr instance);
    partial void Deletet_usr(t_usr instance);
    partial void Insertt_lph(t_lph instance);
    partial void Updatet_lph(t_lph instance);
    partial void Deletet_lph(t_lph instance);
    partial void Insertt_ref(t_ref instance);
    partial void Updatet_ref(t_ref instance);
    partial void Deletet_ref(t_ref instance);
    partial void Insertt_reg(t_reg instance);
    partial void Updatet_reg(t_reg instance);
    partial void Deletet_reg(t_reg instance);
    #endregion
		
		public dcReg() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbRegConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcReg(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcReg(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcReg(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcReg(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_log> t_logs
		{
			get
			{
				return this.GetTable<t_log>();
			}
		}
		
		public System.Data.Linq.Table<t_usr> t_usrs
		{
			get
			{
				return this.GetTable<t_usr>();
			}
		}
		
		public System.Data.Linq.Table<t_lph> t_lphs
		{
			get
			{
				return this.GetTable<t_lph>();
			}
		}
		
		public System.Data.Linq.Table<t_ref> t_refs
		{
			get
			{
				return this.GetTable<t_ref>();
			}
		}
		
		public System.Data.Linq.Table<t_reg> t_regs
		{
			get
			{
				return this.GetTable<t_reg>();
			}
		}
		
		public System.Data.Linq.Table<vw_reg> vw_regs
		{
			get
			{
				return this.GetTable<vw_reg>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Log_Insert")]
		public int sp_Log_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idreg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string keterangan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idreg, status, keterangan, userid);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_log")]
	public partial class t_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _log_id;
		
		private System.Nullable<int> _id_reg;
		
		private System.Nullable<System.DateTime> _tanggal;
		
		private System.Nullable<short> _status;
		
		private string _keterangan;
		
		private string _userid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void Onid_regChanging(System.Nullable<int> value);
    partial void Onid_regChanged();
    partial void OntanggalChanging(System.Nullable<System.DateTime> value);
    partial void OntanggalChanged();
    partial void OnstatusChanging(System.Nullable<short> value);
    partial void OnstatusChanged();
    partial void OnketeranganChanging(string value);
    partial void OnketeranganChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    #endregion
		
		public t_log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reg", DbType="Int")]
		public System.Nullable<int> id_reg
		{
			get
			{
				return this._id_reg;
			}
			set
			{
				if ((this._id_reg != value))
				{
					this.Onid_regChanging(value);
					this.SendPropertyChanging();
					this._id_reg = value;
					this.SendPropertyChanged("id_reg");
					this.Onid_regChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="SmallInt")]
		public System.Nullable<short> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keterangan", DbType="VarChar(200)")]
		public string keterangan
		{
			get
			{
				return this._keterangan;
			}
			set
			{
				if ((this._keterangan != value))
				{
					this.OnketeranganChanging(value);
					this.SendPropertyChanging();
					this._keterangan = value;
					this.SendPropertyChanged("keterangan");
					this.OnketeranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="VarChar(50)")]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_usr")]
	public partial class t_usr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userid;
		
		private string _role;
		
		private string _nama;
		
		private string _title;
		
		private string _psswd;
		
		private System.Nullable<System.DateTime> _last_login;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnpsswdChanging(string value);
    partial void OnpsswdChanged();
    partial void Onlast_loginChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_loginChanged();
    #endregion
		
		public t_usr()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(5)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_psswd", DbType="VarChar(50)")]
		public string psswd
		{
			get
			{
				return this._psswd;
			}
			set
			{
				if ((this._psswd != value))
				{
					this.OnpsswdChanging(value);
					this.SendPropertyChanging();
					this._psswd = value;
					this.SendPropertyChanged("psswd");
					this.OnpsswdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_login
		{
			get
			{
				return this._last_login;
			}
			set
			{
				if ((this._last_login != value))
				{
					this.Onlast_loginChanging(value);
					this.SendPropertyChanging();
					this._last_login = value;
					this.SendPropertyChanged("last_login");
					this.Onlast_loginChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_lph")]
	public partial class t_lph : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lph_id;
		
		private string _lph_code;
		
		private string _nama_lph;
		
		private string _alamat;
		
		private string _kota;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlph_idChanging(int value);
    partial void Onlph_idChanged();
    partial void Onlph_codeChanging(string value);
    partial void Onlph_codeChanged();
    partial void Onnama_lphChanging(string value);
    partial void Onnama_lphChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnkotaChanging(string value);
    partial void OnkotaChanged();
    #endregion
		
		public t_lph()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lph_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int lph_id
		{
			get
			{
				return this._lph_id;
			}
			set
			{
				if ((this._lph_id != value))
				{
					this.Onlph_idChanging(value);
					this.SendPropertyChanging();
					this._lph_id = value;
					this.SendPropertyChanged("lph_id");
					this.Onlph_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lph_code", DbType="VarChar(20)")]
		public string lph_code
		{
			get
			{
				return this._lph_code;
			}
			set
			{
				if ((this._lph_code != value))
				{
					this.Onlph_codeChanging(value);
					this.SendPropertyChanging();
					this._lph_code = value;
					this.SendPropertyChanged("lph_code");
					this.Onlph_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_lph", DbType="VarChar(200)")]
		public string nama_lph
		{
			get
			{
				return this._nama_lph;
			}
			set
			{
				if ((this._nama_lph != value))
				{
					this.Onnama_lphChanging(value);
					this.SendPropertyChanging();
					this._nama_lph = value;
					this.SendPropertyChanged("nama_lph");
					this.Onnama_lphChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(200)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota", DbType="VarChar(50)")]
		public string kota
		{
			get
			{
				return this._kota;
			}
			set
			{
				if ((this._kota != value))
				{
					this.OnkotaChanging(value);
					this.SendPropertyChanging();
					this._kota = value;
					this.SendPropertyChanged("kota");
					this.OnkotaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_ref")]
	public partial class t_ref : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ref_id;
		
		private string _ref_group_id;
		
		private string _ref_desc;
		
		private System.Nullable<short> _f_aktif;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onref_idChanging(string value);
    partial void Onref_idChanged();
    partial void Onref_group_idChanging(string value);
    partial void Onref_group_idChanged();
    partial void Onref_descChanging(string value);
    partial void Onref_descChanged();
    partial void Onf_aktifChanging(System.Nullable<short> value);
    partial void Onf_aktifChanged();
    #endregion
		
		public t_ref()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_id", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ref_id
		{
			get
			{
				return this._ref_id;
			}
			set
			{
				if ((this._ref_id != value))
				{
					this.Onref_idChanging(value);
					this.SendPropertyChanging();
					this._ref_id = value;
					this.SendPropertyChanged("ref_id");
					this.Onref_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_group_id", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ref_group_id
		{
			get
			{
				return this._ref_group_id;
			}
			set
			{
				if ((this._ref_group_id != value))
				{
					this.Onref_group_idChanging(value);
					this.SendPropertyChanging();
					this._ref_group_id = value;
					this.SendPropertyChanged("ref_group_id");
					this.Onref_group_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_desc", DbType="VarChar(50)")]
		public string ref_desc
		{
			get
			{
				return this._ref_desc;
			}
			set
			{
				if ((this._ref_desc != value))
				{
					this.Onref_descChanging(value);
					this.SendPropertyChanging();
					this._ref_desc = value;
					this.SendPropertyChanged("ref_desc");
					this.Onref_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_aktif", DbType="SmallInt")]
		public System.Nullable<short> f_aktif
		{
			get
			{
				return this._f_aktif;
			}
			set
			{
				if ((this._f_aktif != value))
				{
					this.Onf_aktifChanging(value);
					this.SendPropertyChanging();
					this._f_aktif = value;
					this.SendPropertyChanged("f_aktif");
					this.Onf_aktifChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_reg")]
	public partial class t_reg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_reg;
		
		private string _no_daftar;
		
		private System.Nullable<System.DateTime> _tgl_daftar;
		
		private string _nama_pu;
		
		private string _alamat_pu;
		
		private string _kota_pu;
		
		private string _jenis_usaha;
		
		private string _email;
		
		private string _no_telp;
		
		private string _jenis_daftar;
		
		private string _no_surat_pengantar;
		
		private System.Nullable<System.DateTime> _tgl_surat_pengantar;
		
		private string _status_kirim;
		
		private string _penerima;
		
		private System.Nullable<System.DateTime> _tgl_kirim;
		
		private string _file_surat_pengantar;
		
		private string _file_tanda_terima;
		
		private string _file_formulir;
		
		private string _file_verifikasi;
		
		private System.Nullable<int> _lph_id;
		
		private string _status_reg;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_regChanging(int value);
    partial void Onid_regChanged();
    partial void Onno_daftarChanging(string value);
    partial void Onno_daftarChanged();
    partial void Ontgl_daftarChanging(System.Nullable<System.DateTime> value);
    partial void Ontgl_daftarChanged();
    partial void Onnama_puChanging(string value);
    partial void Onnama_puChanged();
    partial void Onalamat_puChanging(string value);
    partial void Onalamat_puChanged();
    partial void Onkota_puChanging(string value);
    partial void Onkota_puChanged();
    partial void Onjenis_usahaChanging(string value);
    partial void Onjenis_usahaChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onno_telpChanging(string value);
    partial void Onno_telpChanged();
    partial void Onjenis_daftarChanging(string value);
    partial void Onjenis_daftarChanged();
    partial void Onno_surat_pengantarChanging(string value);
    partial void Onno_surat_pengantarChanged();
    partial void Ontgl_surat_pengantarChanging(System.Nullable<System.DateTime> value);
    partial void Ontgl_surat_pengantarChanged();
    partial void Onstatus_kirimChanging(string value);
    partial void Onstatus_kirimChanged();
    partial void OnpenerimaChanging(string value);
    partial void OnpenerimaChanged();
    partial void Ontgl_kirimChanging(System.Nullable<System.DateTime> value);
    partial void Ontgl_kirimChanged();
    partial void Onfile_surat_pengantarChanging(string value);
    partial void Onfile_surat_pengantarChanged();
    partial void Onfile_tanda_terimaChanging(string value);
    partial void Onfile_tanda_terimaChanged();
    partial void Onfile_formulirChanging(string value);
    partial void Onfile_formulirChanged();
    partial void Onfile_verifikasiChanging(string value);
    partial void Onfile_verifikasiChanged();
    partial void Onlph_idChanging(System.Nullable<int> value);
    partial void Onlph_idChanged();
    partial void Onstatus_regChanging(string value);
    partial void Onstatus_regChanged();
    #endregion
		
		public t_reg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reg", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_reg
		{
			get
			{
				return this._id_reg;
			}
			set
			{
				if ((this._id_reg != value))
				{
					this.Onid_regChanging(value);
					this.SendPropertyChanging();
					this._id_reg = value;
					this.SendPropertyChanged("id_reg");
					this.Onid_regChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_daftar", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string no_daftar
		{
			get
			{
				return this._no_daftar;
			}
			set
			{
				if ((this._no_daftar != value))
				{
					this.Onno_daftarChanging(value);
					this.SendPropertyChanging();
					this._no_daftar = value;
					this.SendPropertyChanged("no_daftar");
					this.Onno_daftarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_daftar", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> tgl_daftar
		{
			get
			{
				return this._tgl_daftar;
			}
			set
			{
				if ((this._tgl_daftar != value))
				{
					this.Ontgl_daftarChanging(value);
					this.SendPropertyChanging();
					this._tgl_daftar = value;
					this.SendPropertyChanged("tgl_daftar");
					this.Ontgl_daftarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_pu", DbType="VarChar(100)")]
		public string nama_pu
		{
			get
			{
				return this._nama_pu;
			}
			set
			{
				if ((this._nama_pu != value))
				{
					this.Onnama_puChanging(value);
					this.SendPropertyChanging();
					this._nama_pu = value;
					this.SendPropertyChanged("nama_pu");
					this.Onnama_puChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat_pu", DbType="VarChar(100)")]
		public string alamat_pu
		{
			get
			{
				return this._alamat_pu;
			}
			set
			{
				if ((this._alamat_pu != value))
				{
					this.Onalamat_puChanging(value);
					this.SendPropertyChanging();
					this._alamat_pu = value;
					this.SendPropertyChanged("alamat_pu");
					this.Onalamat_puChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota_pu", DbType="VarChar(50)")]
		public string kota_pu
		{
			get
			{
				return this._kota_pu;
			}
			set
			{
				if ((this._kota_pu != value))
				{
					this.Onkota_puChanging(value);
					this.SendPropertyChanging();
					this._kota_pu = value;
					this.SendPropertyChanged("kota_pu");
					this.Onkota_puChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_usaha", DbType="VarChar(20)")]
		public string jenis_usaha
		{
			get
			{
				return this._jenis_usaha;
			}
			set
			{
				if ((this._jenis_usaha != value))
				{
					this.Onjenis_usahaChanging(value);
					this.SendPropertyChanging();
					this._jenis_usaha = value;
					this.SendPropertyChanged("jenis_usaha");
					this.Onjenis_usahaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_telp", DbType="VarChar(20)")]
		public string no_telp
		{
			get
			{
				return this._no_telp;
			}
			set
			{
				if ((this._no_telp != value))
				{
					this.Onno_telpChanging(value);
					this.SendPropertyChanging();
					this._no_telp = value;
					this.SendPropertyChanged("no_telp");
					this.Onno_telpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_daftar", DbType="VarChar(20)")]
		public string jenis_daftar
		{
			get
			{
				return this._jenis_daftar;
			}
			set
			{
				if ((this._jenis_daftar != value))
				{
					this.Onjenis_daftarChanging(value);
					this.SendPropertyChanging();
					this._jenis_daftar = value;
					this.SendPropertyChanged("jenis_daftar");
					this.Onjenis_daftarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_surat_pengantar", DbType="VarChar(50)")]
		public string no_surat_pengantar
		{
			get
			{
				return this._no_surat_pengantar;
			}
			set
			{
				if ((this._no_surat_pengantar != value))
				{
					this.Onno_surat_pengantarChanging(value);
					this.SendPropertyChanging();
					this._no_surat_pengantar = value;
					this.SendPropertyChanged("no_surat_pengantar");
					this.Onno_surat_pengantarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_surat_pengantar", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> tgl_surat_pengantar
		{
			get
			{
				return this._tgl_surat_pengantar;
			}
			set
			{
				if ((this._tgl_surat_pengantar != value))
				{
					this.Ontgl_surat_pengantarChanging(value);
					this.SendPropertyChanging();
					this._tgl_surat_pengantar = value;
					this.SendPropertyChanged("tgl_surat_pengantar");
					this.Ontgl_surat_pengantarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_kirim", DbType="VarChar(5)")]
		public string status_kirim
		{
			get
			{
				return this._status_kirim;
			}
			set
			{
				if ((this._status_kirim != value))
				{
					this.Onstatus_kirimChanging(value);
					this.SendPropertyChanging();
					this._status_kirim = value;
					this.SendPropertyChanged("status_kirim");
					this.Onstatus_kirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_penerima", DbType="VarChar(100)")]
		public string penerima
		{
			get
			{
				return this._penerima;
			}
			set
			{
				if ((this._penerima != value))
				{
					this.OnpenerimaChanging(value);
					this.SendPropertyChanging();
					this._penerima = value;
					this.SendPropertyChanged("penerima");
					this.OnpenerimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_kirim", DbType="DateTime")]
		public System.Nullable<System.DateTime> tgl_kirim
		{
			get
			{
				return this._tgl_kirim;
			}
			set
			{
				if ((this._tgl_kirim != value))
				{
					this.Ontgl_kirimChanging(value);
					this.SendPropertyChanging();
					this._tgl_kirim = value;
					this.SendPropertyChanged("tgl_kirim");
					this.Ontgl_kirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_surat_pengantar", DbType="VarChar(50)")]
		public string file_surat_pengantar
		{
			get
			{
				return this._file_surat_pengantar;
			}
			set
			{
				if ((this._file_surat_pengantar != value))
				{
					this.Onfile_surat_pengantarChanging(value);
					this.SendPropertyChanging();
					this._file_surat_pengantar = value;
					this.SendPropertyChanged("file_surat_pengantar");
					this.Onfile_surat_pengantarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_tanda_terima", DbType="VarChar(50)")]
		public string file_tanda_terima
		{
			get
			{
				return this._file_tanda_terima;
			}
			set
			{
				if ((this._file_tanda_terima != value))
				{
					this.Onfile_tanda_terimaChanging(value);
					this.SendPropertyChanging();
					this._file_tanda_terima = value;
					this.SendPropertyChanged("file_tanda_terima");
					this.Onfile_tanda_terimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_formulir", DbType="VarChar(50)")]
		public string file_formulir
		{
			get
			{
				return this._file_formulir;
			}
			set
			{
				if ((this._file_formulir != value))
				{
					this.Onfile_formulirChanging(value);
					this.SendPropertyChanging();
					this._file_formulir = value;
					this.SendPropertyChanged("file_formulir");
					this.Onfile_formulirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_verifikasi", DbType="VarChar(50)")]
		public string file_verifikasi
		{
			get
			{
				return this._file_verifikasi;
			}
			set
			{
				if ((this._file_verifikasi != value))
				{
					this.Onfile_verifikasiChanging(value);
					this.SendPropertyChanging();
					this._file_verifikasi = value;
					this.SendPropertyChanged("file_verifikasi");
					this.Onfile_verifikasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lph_id", DbType="Int")]
		public System.Nullable<int> lph_id
		{
			get
			{
				return this._lph_id;
			}
			set
			{
				if ((this._lph_id != value))
				{
					this.Onlph_idChanging(value);
					this.SendPropertyChanging();
					this._lph_id = value;
					this.SendPropertyChanged("lph_id");
					this.Onlph_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_reg", DbType="VarChar(5)")]
		public string status_reg
		{
			get
			{
				return this._status_reg;
			}
			set
			{
				if ((this._status_reg != value))
				{
					this.Onstatus_regChanging(value);
					this.SendPropertyChanging();
					this._status_reg = value;
					this.SendPropertyChanged("status_reg");
					this.Onstatus_regChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_reg")]
	public partial class vw_reg
	{
		
		private int _id_reg;
		
		private string _no_daftar;
		
		private System.Nullable<System.DateTime> _tgl_daftar;
		
		private string _nama_pu;
		
		private string _alamat_pu;
		
		private string _kota_pu;
		
		private string _jenis_usaha;
		
		private string _email;
		
		private string _no_telp;
		
		private string _jenis_daftar;
		
		private string _no_surat_pengantar;
		
		private System.Nullable<System.DateTime> _tgl_surat_pengantar;
		
		private string _status_kirim;
		
		private string _penerima;
		
		private System.Nullable<System.DateTime> _tgl_kirim;
		
		private string _file_surat_pengantar;
		
		private string _file_tanda_terima;
		
		private string _file_formulir;
		
		private string _file_verifikasi;
		
		private System.Nullable<int> _lph_id;
		
		private string _nama_jenis_usaha;
		
		private string _nama_jenis_daftar;
		
		private string _nama_status_kirim;
		
		private string _nama_lph;
		
		private string _kota;
		
		private string _status_reg;
		
		private string _nama_status_reg;
		
		public vw_reg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reg", DbType="Int NOT NULL")]
		public int id_reg
		{
			get
			{
				return this._id_reg;
			}
			set
			{
				if ((this._id_reg != value))
				{
					this._id_reg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_daftar", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string no_daftar
		{
			get
			{
				return this._no_daftar;
			}
			set
			{
				if ((this._no_daftar != value))
				{
					this._no_daftar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_daftar", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> tgl_daftar
		{
			get
			{
				return this._tgl_daftar;
			}
			set
			{
				if ((this._tgl_daftar != value))
				{
					this._tgl_daftar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_pu", DbType="VarChar(100)")]
		public string nama_pu
		{
			get
			{
				return this._nama_pu;
			}
			set
			{
				if ((this._nama_pu != value))
				{
					this._nama_pu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat_pu", DbType="VarChar(100)")]
		public string alamat_pu
		{
			get
			{
				return this._alamat_pu;
			}
			set
			{
				if ((this._alamat_pu != value))
				{
					this._alamat_pu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota_pu", DbType="VarChar(50)")]
		public string kota_pu
		{
			get
			{
				return this._kota_pu;
			}
			set
			{
				if ((this._kota_pu != value))
				{
					this._kota_pu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_usaha", DbType="VarChar(20)")]
		public string jenis_usaha
		{
			get
			{
				return this._jenis_usaha;
			}
			set
			{
				if ((this._jenis_usaha != value))
				{
					this._jenis_usaha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_telp", DbType="VarChar(20)")]
		public string no_telp
		{
			get
			{
				return this._no_telp;
			}
			set
			{
				if ((this._no_telp != value))
				{
					this._no_telp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_daftar", DbType="VarChar(20)")]
		public string jenis_daftar
		{
			get
			{
				return this._jenis_daftar;
			}
			set
			{
				if ((this._jenis_daftar != value))
				{
					this._jenis_daftar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_surat_pengantar", DbType="VarChar(50)")]
		public string no_surat_pengantar
		{
			get
			{
				return this._no_surat_pengantar;
			}
			set
			{
				if ((this._no_surat_pengantar != value))
				{
					this._no_surat_pengantar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_surat_pengantar", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> tgl_surat_pengantar
		{
			get
			{
				return this._tgl_surat_pengantar;
			}
			set
			{
				if ((this._tgl_surat_pengantar != value))
				{
					this._tgl_surat_pengantar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_kirim", DbType="VarChar(5)")]
		public string status_kirim
		{
			get
			{
				return this._status_kirim;
			}
			set
			{
				if ((this._status_kirim != value))
				{
					this._status_kirim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_penerima", DbType="VarChar(100)")]
		public string penerima
		{
			get
			{
				return this._penerima;
			}
			set
			{
				if ((this._penerima != value))
				{
					this._penerima = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_kirim", DbType="DateTime")]
		public System.Nullable<System.DateTime> tgl_kirim
		{
			get
			{
				return this._tgl_kirim;
			}
			set
			{
				if ((this._tgl_kirim != value))
				{
					this._tgl_kirim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_surat_pengantar", DbType="VarChar(50)")]
		public string file_surat_pengantar
		{
			get
			{
				return this._file_surat_pengantar;
			}
			set
			{
				if ((this._file_surat_pengantar != value))
				{
					this._file_surat_pengantar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_tanda_terima", DbType="VarChar(50)")]
		public string file_tanda_terima
		{
			get
			{
				return this._file_tanda_terima;
			}
			set
			{
				if ((this._file_tanda_terima != value))
				{
					this._file_tanda_terima = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_formulir", DbType="VarChar(50)")]
		public string file_formulir
		{
			get
			{
				return this._file_formulir;
			}
			set
			{
				if ((this._file_formulir != value))
				{
					this._file_formulir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_verifikasi", DbType="VarChar(50)")]
		public string file_verifikasi
		{
			get
			{
				return this._file_verifikasi;
			}
			set
			{
				if ((this._file_verifikasi != value))
				{
					this._file_verifikasi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lph_id", DbType="Int")]
		public System.Nullable<int> lph_id
		{
			get
			{
				return this._lph_id;
			}
			set
			{
				if ((this._lph_id != value))
				{
					this._lph_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_jenis_usaha", DbType="VarChar(50)")]
		public string nama_jenis_usaha
		{
			get
			{
				return this._nama_jenis_usaha;
			}
			set
			{
				if ((this._nama_jenis_usaha != value))
				{
					this._nama_jenis_usaha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_jenis_daftar", DbType="VarChar(50)")]
		public string nama_jenis_daftar
		{
			get
			{
				return this._nama_jenis_daftar;
			}
			set
			{
				if ((this._nama_jenis_daftar != value))
				{
					this._nama_jenis_daftar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_status_kirim", DbType="VarChar(50)")]
		public string nama_status_kirim
		{
			get
			{
				return this._nama_status_kirim;
			}
			set
			{
				if ((this._nama_status_kirim != value))
				{
					this._nama_status_kirim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_lph", DbType="VarChar(200)")]
		public string nama_lph
		{
			get
			{
				return this._nama_lph;
			}
			set
			{
				if ((this._nama_lph != value))
				{
					this._nama_lph = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota", DbType="VarChar(50)")]
		public string kota
		{
			get
			{
				return this._kota;
			}
			set
			{
				if ((this._kota != value))
				{
					this._kota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_reg", DbType="VarChar(5)")]
		public string status_reg
		{
			get
			{
				return this._status_reg;
			}
			set
			{
				if ((this._status_reg != value))
				{
					this._status_reg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_status_reg", DbType="VarChar(50)")]
		public string nama_status_reg
		{
			get
			{
				return this._nama_status_reg;
			}
			set
			{
				if ((this._nama_status_reg != value))
				{
					this._nama_status_reg = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
